# Generated by Django 5.2.1 on 2025-05-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_alter_venta_options_venta_distribuidor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="noticias/"),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
